# Generated by Django 2.1.5 on 2020-05-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additional_info',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='colour',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='internal_comment',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='ip',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='size_description',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Хүсэлт илгээсэн', 'Хүсэлт илгээсэн'), ('Хариу ирсэн', ' Хариу ирсэн'), ('Бараа захиалга хийгдсэн', 'Бараа захиалга хийгдсэн'), ('Бараа худалдан авалт хийгдсэн', 'Бараа худалдан авалт хийгдсэн'), ('Бараа Англи дахь хаягт ирсэн', 'Бараа Англи дахь хаягт ирсэн'), ('Бараа Англиас илгээгдсэн', 'Бараа Англиас илгээгдсэн'), ('Замдаа', 'Замдаа'), ('Бараа гааль дээр', 'Бараа гааль дээр'), ('Бараа авахад бэлэн', 'Бараа авахад бэлэн'), ('Хүлээлгэн өгсөн', 'Хүлээлгэн өгсөн')], default='Хүсэлт илгээсэн', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='telephone',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_link',
            field=models.CharField(default='', max_length=254),
        ),
    ]
