# Generated by Django 2.1.5 on 2020-06-03 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200525_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('gbp_amount', models.IntegerField(default=1)),
                ('gbpToMntDailyRate', models.IntegerField(default=1)),
                ('mnt_amount', models.IntegerField(default=1)),
                ('reference_id', models.IntegerField(default=1)),
                ('direction', models.CharField(default='', max_length=64)),
                ('reciever_name', models.CharField(default='', max_length=64)),
                ('reciever_telephone', models.CharField(default='', max_length=64)),
                ('reciever_email', models.CharField(default='', max_length=64)),
                ('reciever_register', models.CharField(default='', max_length=64)),
                ('reciever_bank', models.CharField(default='', max_length=64)),
                ('reciever_account', models.CharField(default='', max_length=64)),
                ('sender_name', models.CharField(default='', max_length=64)),
                ('sender_telephone', models.CharField(default='', max_length=64)),
                ('sender_email', models.CharField(default='', max_length=64)),
                ('sender_postcode', models.CharField(default='', max_length=64)),
                ('sender_ip', models.CharField(default='', max_length=64)),
                ('additional_info', models.CharField(default='', max_length=254)),
                ('ip', models.CharField(default='', max_length=64)),
                ('internal_comment', models.CharField(default='', max_length=254)),
                ('order_id', models.IntegerField(default=1, null=True)),
                ('status', models.CharField(choices=[('Хүсэлт илгээсэн', 'Хүсэлт илгээсэн'), ('Хариу ирсэн', ' Хариу ирсэн'), ('Шилжүүлэгч шилжүүлсэн', 'Шилжүүлэгч шилжүүлсэн'), ('Систем шалгаж байна', 'Систем шалгаж байна'), ('Хүлээн авагч руу шилжүүлсэн', 'Хүлээн авагч руу шилжүүлсэн'), ('Хүлээн авагчийн мэдээлэл буруу', 'Хүлээн авагчийн мэдээлэл буруу'), ('Хүлээгдэж байна', 'Хүлээгдэж байна')], default='Хүсэлт илгээсэн', max_length=64)),
            ],
        ),
    ]
