# Generated by Django 2.1.5 on 2020-06-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_transfer_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_order',
            name='gbpToMntDailyRate',
            field=models.FloatField(default=1),
        ),
    ]
