# Generated by Django 2.1.5 on 2020-06-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200605_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_order',
            name='gbp_amount',
            field=models.CharField(default=1, max_length=254),
        ),
        migrations.AlterField(
            model_name='transfer_order',
            name='mnt_amount',
            field=models.CharField(default=1, max_length=254),
        ),
    ]
