# Generated by Django 2.1.5 on 2020-06-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200605_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer_order',
            name='directionName',
            field=models.CharField(default='', max_length=64),
        ),
    ]
